### PR TITLE
add option to color outdated formulae

### PR DESCRIPTION
**Pull request by kbrock**
When I am prompted to update software, I often wonder if I can just delete it instead

I updated your great script to highlight outdated formulae in red.

- Not sure about your color preferences.
- Only tested with `graphviz`
- if you have a preference instead of the double ternary (`?:?:`), just say so.

```bash
brew graph --outdated --installed --highlight-leaves | dot -Tpng -ograph.png
```

### CODE REVIEW

**Comment by martido** [comment]
Nice idea, thanks! Will check it out in the next couple of days.

**Comment by martido** [comment]
I'm very sorry that it took me so long to get back to you. I really like the idea. Thanks for contributing! I'll add a corresponding option to support GraphML. Also, if you don't mind, I'd like to rename the command line option to "highlight-outdated" to keep it consistent with the existing switch "highlight-leaves", and disable it by default.

**Comment by kbrock** [comment]
@martido ugh - just saw this. you want me to follow up with ^ ?

**Comment by kbrock** [comment]
ooh - you did already. sweet.  thanks

**Pull request merged**
